#application/deployment.yaml 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simpleapp-deployment
spec:
  selector:
    matchLabels:
      app: simpleapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: mondosage/simpleapp:latest
        ports:
        - containerPort: 80
